apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ete-training
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ete-training
  policy:
    semver:
      range: x.x.x
